#!/usr/bin/env zsh
typeset -a columns files
typeset foundsep last program

printusage() {
    print 'usage: csvread [arguments] columns... file'
    print 'usage: csvread [arguments] columns... -- files...'
    print
    print 'Arguments:'
    print '   -h --help  show usage'
    print
    print 'If -- is not found, the last positional argument is considered a file path'
    exit
}

zparseopts -D -K -E \
    h=help -help=help

[[ $# -eq 0 || -n $help ]] && printusage

for arg in $@; do
    if [[ $arg == '--' ]]; then
        foundsep=1
    fi
    if (( foundsep )); then
        files+=($arg)
    else
        columns+=($arg)
        last=$arg
    fi
done

if [[ -z $files ]]; then
    files+=($last)
    columns=($columns[1,-2])
fi

${0:a:h}/csvawk "{ print [${(j:], [:)columns}] }" $files
