#!/usr/bin/env zsh
typeset -a columns files
typeset foundsep last program

zparseopts -D -K -E \
    h=help -help=help

if [[ $# -eq 0 || -n $help ]]; then
    print 'usage: csvread [arguments] [columns...] [--] [files...]'
    print
    print 'Arguments:'
    print '   --         only file names after this'
    print '   -h --help  show usage'
    print
    print 'If -- is not found, the last positional argument is considered a file path'
fi

for arg in $@; do
    if [[ $arg == '--' ]]; then
        foundsep=1
    fi
    if (( foundsep )); then
        files+=($arg)
    else
        columns+=($arg)
        last=$arg
    fi
done

if [[ -z $files ]]; then
    files+=($last)
    columns=($columns[1,-2])
fi

${0:a:h}/csvawk "{ print [${(j:], [:)columns}] }" $files
